#ifndef C2023_CHALLENGE_BASICAL_PARAMETER_H
#define C2023_CHALLENGE_BASICAL_PARAMETER_H
#include <stdio.h>
#define TRAIN_TIMES 1
#define TRAIN_DATA_CAPACITY 60000
#define PHOTO_SIZE 28
#define INPUT_NUMBER 784
#define HIDDEN_NUMBER 50
#define OUTPUT_NUMBER 10
#define TEST_DATA_CAPACITY 10000
#define ALPHA 0.2//定义学习率
#endif //C2023_CHALLENGE_BASICAL_PARAMETER_H
